#!/bin/bash
# This hook installs the dependencies needed to run the charm,
# creates the dispatch executable, regenerates the symlinks for start and
# upgrade-charm, and kicks off the operator framework.

set -e

# Source the os-release information into the env
. /etc/os-release

if ! [[ -f '.installed' ]]
then
	if [[ $ID == 'centos' ]]
	then
		# Necessary to compile and install NHC
		yum -y install make

		# Determine the centos version and install prereqs accordingly
		if [[ $VERSION_ID == "7" ]]
		then
			/bin/bash ./src/scripts/install_python.sh
		elif [[ $VERSION_ID == "9" ]]
		then
			yum -y install python38
		fi
	elif [[ $ID == 'ubuntu' ]]
	then
		# Necessary to compile and install NHC
		apt-get install --assume-yes make
	fi
	touch .installed
fi

# set the correct python bin path
if [[ $ID == "centos" && $VERSION_ID == "7" ]]
then
	PYTHON_BIN=/opt/python/3.8.16/bin/python3.8
else
	PYTHON_BIN=/usr/bin/python3
fi

JUJU_DISPATCH_PATH="${JUJU_DISPATCH_PATH:-$0}" PYTHONPATH=lib:venv $PYTHON_BIN ./src/charm.py